build:
  script:
  - mvn clean install --settings /home/gitlab-runner/settings.xml
  - find .
  artifacts:
    paths:
    - */target/*.jar
  only:
  - master
  stage: build

deploy:
  script:
  - mvn deploy --settings /home/gitlab-runner/settings.xml
  only:
  - master
  stage: deploy
