name: MCONE-Lobby
author: TwinsterHD
version: 2.5
main: eu.mcone.lobby.Main
depend: [McOne-BukkitCoreSystem]
commands:
  set:
    description: Setze die einzelnen Spielmodi
  setholo:
    description: Setze die einzelnen Hologramme
  npc:
    descirption: Spawnt einen NPC
  spawn:
    description: Teleportiert den Spieler zum Spawn
